# vim: ft=yaml
name: test

on:
  - push
  - pull_request

jobs:
  rspec:
    name: Ruby ${{ matrix.ruby }} / ${{ matrix.gemfile }}
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        ruby:
          - "3.3"
          - "3.2"
          - "3.1"
        gemfile:
          - rails_6.1.gemfile
          - rails_7.0.gemfile
          - rails_7.1.gemfile
          - rails_7.2.gemfile
          - rack_2.0.gemfile
          - rack_2.1.gemfile
          - rack_2.2.gemfile
          - sidekiq_6.gemfile
          - sidekiq_7.gemfile
      fail-fast: false

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}
      BUNDLE_WITHOUT: development
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3

    steps:
      - uses: actions/checkout@master

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rspec --color --format documentation

  rubocop:
    name: rubocop
    runs-on: ubuntu-22.04

    env:
      BUNDLE_WITHOUT: development
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3

    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - run: bundle exec rubocop --parallel --color
